import { Product } from "./schemas";

export const CATEGORIES = [
    { slug: "spirits", name: "Spirits" },
    { slug: "wine", name: "Wine" },
    { slug: "beer", name: "Beer" },
    { slug: "seltzers", name: "Seltzers" },
] as const;

export const MOCK_PRODUCTS: Product[] = [
    {
        id: "1",
        slug: "titos-handmade-vodka",
        name: "Tito's Handmade Vodka",
        brand: "Tito's",
        category: "spirits",
        subCategory: "vodka",
        price: 32.99,
        size: "1.75L",
        abv: 40,
        images: ["/placeholder.jpg"],
        description: "Americas Original Craft Vodka. Produced in Austin, Texas.",
        tags: ["gluten-free", "bestseller"],
        inStock: true,
        isAlcohol: true,
        variants: [],
    },
    {
        id: "2",
        slug: "casamigos-blanco-tequila",
        name: "Casamigos Blanco Tequila",
        brand: "Casamigos",
        category: "spirits",
        subCategory: "tequila",
        price: 45.99,
        size: "750ml",
        abv: 40,
        images: ["/placeholder.jpg"],
        description: "Crisp and clean with hints of citrus, vanilla and sweet agave.",
        tags: ["premium"],
        inStock: true,
        isAlcohol: true,
        variants: [],
    },
    {
        id: "3",
        slug: "jameson-irish-whiskey",
        name: "Jameson Irish Whiskey",
        brand: "Jameson",
        category: "spirits",
        subCategory: "whiskey",
        price: 29.99,
        size: "750ml",
        abv: 40,
        images: ["/placeholder.jpg"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "4",
        slug: "josh-cellars-cabernet-sauvignon",
        name: "Josh Cellars Cabernet Sauvignon",
        brand: "Josh Cellars",
        category: "wine",
        subCategory: "red wine",
        price: 14.99,
        size: "750ml",
        abv: 13.5,
        images: ["/placeholder.jpg"],
        description: "The bouquet is rich with dark fruits, cinnamon, clove and subtle oak aromas.",
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "5",
        slug: "kim-crawford-sauvignon-blanc",
        name: "Kim Crawford Sauvignon Blanc",
        brand: "Kim Crawford",
        category: "wine",
        subCategory: "white wine",
        price: 15.99,
        size: "750ml",
        abv: 13,
        images: ["/placeholder.jpg"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "6",
        slug: "corona-extra-12pk",
        name: "Corona Extra 12 Pack",
        brand: "Corona",
        category: "beer",
        subCategory: "lager",
        price: 18.99,
        size: "12 oz bottles",
        abv: 4.6,
        images: ["/placeholder.jpg"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "7",
        slug: "stella-artois-6pk",
        name: "Stella Artois 6 Pack",
        brand: "Stella Artois",
        category: "beer",
        subCategory: "lager",
        price: 10.99,
        size: "11.2 oz bottles",
        abv: 5,
        images: ["/placeholder.jpg"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "8",
        slug: "white-claw-variety-pack",
        name: "White Claw Variety Pack 12pk",
        brand: "White Claw",
        category: "seltzers",
        subCategory: "variety",
        price: 19.99,
        size: "12 oz cans",
        abv: 5,
        images: ["/placeholder.jpg"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "9",
        slug: "veuve-clicquot-brut",
        name: "Veuve Clicquot Yellow Label Brut",
        brand: "Veuve Clicquot",
        category: "wine",
        subCategory: "champagne",
        price: 69.99,
        size: "750ml",
        abv: 12,
        images: ["/placeholder.jpg"],
        tags: ["luxury", "gift"],
        inStock: true,
        isAlcohol: true,
        variants: [],
    },
    {
        id: "10",
        slug: "hennessy-vs-cognac",
        name: "Hennessy VS Cognac",
        brand: "Hennessy",
        category: "spirits",
        subCategory: "cognac",
        price: 42.99,
        size: "750ml",
        abv: 40,
        images: ["/placeholder.jpg"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
];
