import { Product } from "./schemas";

export const CATEGORIES = [
    { slug: "ready-to-drink", name: "Ready to Drink" },
    { slug: "beer", name: "Beer" },
    { slug: "spirits", name: "Spirits" },
    { slug: "wine", name: "Wine" },
    { slug: "seltzer", name: "Seltzers" },
] as const;

export const MOCK_PRODUCTS: Product[] = [
    // Ready-to-drink / Seltzers
    {
        id: "surfside-variety-8pk",
        slug: "surfside-lemonade-variety-pack-vodka-cans",
        name: "Surfside Lemonade Variety Pack Vodka Cans",
        brand: "Surfside",
        category: "ready-to-drink",
        subCategory: "vodka-soda",
        price: 25.73,
        size: "12 fl oz x 8 ct",
        abv: 4.5,
        images: ["https://images.unsplash.com/photo-1624520934861-c67421ae7d6c?q=80&w=800&auto=format&fit=crop"], // Lemonade/Vodka vibe
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: ["variety-pack"],
    },
    {
        id: "white-claw-no3-12pk",
        slug: "white-claw-gluten-free-no-3-hard-seltzer",
        name: "White Claw Gluten Free No. 3 Hard Seltzer",
        brand: "White Claw",
        category: "seltzer",
        subCategory: "variety",
        price: 25.73,
        size: "12 fl oz x 12 ct",
        abv: 5,
        images: ["https://images.unsplash.com/photo-1574686419842-998845701d63?q=80&w=800&auto=format&fit=crop"], // Hard Seltzer
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: ["gluten-free"],
    },
    {
        id: "cutwater-lime-margarita-4pk",
        slug: "cutwater-lime-margarita-cocktail-cans",
        name: "Cutwater Lime Margarita Cocktail Cans",
        brand: "Cutwater",
        category: "ready-to-drink",
        subCategory: "margarita",
        price: 18.71,
        size: "12 fl oz x 4 ct",
        abv: 12.5,
        images: ["https://images.unsplash.com/photo-1568545806669-7c4ad3d9fb38?q=80&w=800&auto=format&fit=crop"], // Margarita
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "smirnoff-ice-party-12pk",
        slug: "smirnoff-ice-malt-beverage-bottles-party-pack",
        name: "Smirnoff Ice Party Pack",
        brand: "Smirnoff",
        category: "ready-to-drink",
        subCategory: "malt-beverage",
        price: 22.22,
        size: "12 fl oz x 12 ct",
        abv: 4.5,
        images: ["https://images.unsplash.com/photo-1629202517878-5749f7e8a937?q=80&w=800&auto=format&fit=crop"], // Colorful drinks
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: ["party-pack"],
    },
    {
        id: "cutwater-long-island-4pk",
        slug: "cutwater-cocktails-long-island-iced-tea",
        name: "Cutwater Long Island Iced Tea",
        brand: "Cutwater",
        category: "ready-to-drink",
        subCategory: "cocktail",
        price: 18.71,
        size: "12 fl oz x 4 ct",
        abv: 13.2,
        images: ["https://images.unsplash.com/photo-1547595628-c61a29f496f0?q=80&w=800&auto=format&fit=crop"], // Iced tea look
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "angry-orchard-6pk",
        slug: "angry-orchard-crisp-apple-hard-cider",
        name: "Angry Orchard Crisp Apple Hard Cider",
        brand: "Angry Orchard",
        category: "beer",
        subCategory: "cider",
        price: 13.99,
        size: "12 fl oz x 6 ct",
        abv: 5,
        images: ["https://images.unsplash.com/photo-1563503521-122e23215272?q=80&w=800&auto=format&fit=crop"], // Cider/Apple
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: ["gluten-free"],
    },
    {
        id: "beatbox-fruit-punch",
        slug: "beatbox-beverages-fruit-punch-cocktail-box",
        name: "Beatbox Fruit Punch Cocktail",
        brand: "Beatbox",
        category: "ready-to-drink",
        subCategory: "punch",
        price: 4.67,
        size: "500 ml",
        abv: 11.1,
        images: ["https://images.unsplash.com/photo-1510626176961-4b57d4fbad03?q=80&w=800&auto=format&fit=crop"], // Punch
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "high-noon-variety-8pk",
        slug: "high-noon-gluten-free-no-added-sugar-hard-seltzer",
        name: "High Noon Variety Pack",
        brand: "High Noon",
        category: "seltzer",
        subCategory: "vodka-soda",
        price: 25.73,
        size: "355 ml x 8 ct",
        abv: 4.5,
        images: ["https://images.unsplash.com/photo-1629007469275-3435b8dd577f?q=80&w=800&auto=format&fit=crop"], // Canned seltzer
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: ["gluten-free", "no-sugar"],
    },

    // Beer / Lager
    {
        id: "coors-light-30pk",
        slug: "coors-light-american-lager-beer-cans-30pk",
        name: "Coors Light American Lager",
        brand: "Coors",
        category: "beer",
        subCategory: "lager",
        price: 31.58,
        size: "12 fl oz x 30 ct",
        abv: 4.2,
        images: ["https://images.unsplash.com/photo-1623055964894-3ca97047814b?q=80&w=800&auto=format&fit=crop"], // Generic beer can
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "miller-lite-12pk",
        slug: "miller-lite-american-pilsner-cans-12pk",
        name: "Miller Lite American Pilsner",
        brand: "Miller",
        category: "beer",
        subCategory: "pilsner",
        price: 18.71,
        size: "12 fl oz x 12 ct",
        abv: 4.2,
        images: ["https://images.unsplash.com/photo-1598463177994-353272d73ae0?q=80&w=800&auto=format&fit=crop"], // Beer
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "modelo-especial-12pk",
        slug: "modelo-especial-mexican-lager-cans",
        name: "Modelo Especial Mexican Lager",
        brand: "Modelo",
        category: "beer",
        subCategory: "lager",
        price: 23.39,
        size: "12 fl oz x 12 ct",
        abv: 4.4,
        images: ["https://images.unsplash.com/photo-1659616182126-7243c9780074?q=80&w=800&auto=format&fit=crop"], // Modeloish
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "stella-artois-12pk",
        slug: "stella-artois-classic-lager-cans",
        name: "Stella Artois Classic Lager",
        brand: "Stella Artois",
        category: "beer",
        subCategory: "lager",
        price: 23.39,
        size: "12 fl oz x 12 ct",
        abv: 5,
        images: ["https://images.unsplash.com/photo-1634575301828-565d70cb3c78?q=80&w=800&auto=format&fit=crop"], // Stella
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "coors-banquet-30pk",
        slug: "coors-banquet-american-lager-cans",
        name: "Coors Banquet American Lager",
        brand: "Coors",
        category: "beer",
        subCategory: "lager",
        price: 32.75,
        size: "12 fl oz x 30 ct",
        abv: 5,
        images: ["https://images.unsplash.com/photo-1662998822960-e8f081736780?q=80&w=800&auto=format&fit=crop"], // Coors
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "corona-extra-24pk",
        slug: "corona-extra-mexican-lager-bottles",
        name: "Corona Extra Mexican Lager",
        brand: "Corona",
        category: "beer",
        subCategory: "lager",
        price: 40.94,
        size: "12 fl oz x 24 ct",
        abv: 4.6,
        images: ["https://images.unsplash.com/photo-1627916942797-17f22a559880?q=80&w=800&auto=format&fit=crop"], // Corona
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },

    // More Beer (Imported/Domestic)
    {
        id: "fosters-premium-ale-can",
        slug: "fosters-premium-ale-lager-can",
        name: "Foster's Premium Ale Lager Can",
        brand: "Foster's",
        category: "beer",
        subCategory: "ale",
        price: 3.51,
        size: "25.4 fl oz",
        abv: 5.5,
        images: ["https://images.unsplash.com/photo-1662998822960-e8f081736780?q=80&w=800&auto=format&fit=crop"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "bud-light-watermelon-rita",
        slug: "bud-light-water-melon-rita-ale-can",
        name: "Bud Light Water-Melon-Rita Ale Can",
        brand: "Bud Light",
        category: "ready-to-drink",
        subCategory: "cocktail",
        price: 4.08,
        size: "25 fl oz",
        abv: 8,
        images: ["https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=800&auto=format&fit=crop"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "budweiser-can-25oz",
        slug: "budweiser-american-lager-beer-can",
        name: "Budweiser American Lager Beer Can",
        brand: "Budweiser",
        category: "beer",
        subCategory: "lager",
        price: 2.91,
        size: "25 fl oz",
        abv: 5,
        images: ["https://images.unsplash.com/photo-1662998822960-e8f081736780?q=80&w=800&auto=format&fit=crop"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "modelo-oro-24oz",
        slug: "modelo-oro-light-gold-standard-lager-can",
        name: "Modelo Oro Light Gold Standard Lager Can",
        brand: "Modelo",
        category: "beer",
        subCategory: "lager",
        price: 4.67,
        size: "24 fl oz",
        abv: 4,
        images: ["https://images.unsplash.com/photo-1659616182126-7243c9780074?q=80&w=800&auto=format&fit=crop"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "becks-6pk",
        slug: "becks-german-pilsner-bottles",
        name: "Beck's German Pilsner Bottles",
        brand: "Beck's",
        category: "beer",
        subCategory: "pilsner",
        price: 11.69,
        size: "12 fl oz x 6 ct",
        abv: 5,
        images: ["https://images.unsplash.com/photo-1566633806327-68e152aaf26d?q=80&w=800&auto=format&fit=crop"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "sagres-6pk",
        slug: "sagres-cerveja-lager-bottles",
        name: "Sagres Cerveja Lager Bottles",
        brand: "Sagres",
        category: "beer",
        subCategory: "lager",
        price: 12.86,
        size: "12 fl oz x 6 ct",
        abv: 5,
        images: ["https://images.unsplash.com/photo-1598463177994-353272d73ae0?q=80&w=800&auto=format&fit=crop"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },

    // Wine
    {
        id: "el-enemigo-cab-franc",
        slug: "el-enemigo-gran-enemigo-cabernet-franc-agrelo",
        name: "El Enemigo Gran Enemigo Cabernet Franc Agrelo",
        brand: "El Enemigo",
        category: "wine",
        subCategory: "red",
        price: 38.60,
        size: "1 L",
        abv: 13.5,
        images: ["https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?q=80&w=800&auto=format&fit=crop"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "megvani-saperavi",
        slug: "megvani-dry-red-saperavi",
        name: "Megvani Dry Red Saperavi",
        brand: "Megvani",
        category: "wine",
        subCategory: "red",
        price: 10.52,
        size: "750 ml",
        abv: 12,
        images: ["https://images.unsplash.com/photo-1559563362-c667ba5f5480?q=80&w=800&auto=format&fit=crop"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "opus-one-magnum",
        slug: "opus-one-cabernet-sauvignon-napa-valley",
        name: "Opus One Cabernet Sauvignon Napa Valley",
        brand: "Opus One",
        category: "wine",
        subCategory: "red",
        price: 18.71,
        size: "1.5 L",
        abv: 14.5,
        images: ["https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?q=80&w=800&auto=format&fit=crop"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: ["premium"],
    },
    {
        id: "barton-guestier-chardonnay",
        slug: "barton-guestier-bistro-chardonnay",
        name: "Barton & Guestier Bistro Chardonnay",
        brand: "Barton & Guestier",
        category: "wine",
        subCategory: "white",
        price: 11.69,
        size: "750 ml",
        abv: 13,
        images: ["https://images.unsplash.com/photo-1584916201218-f4242ceb4809?q=80&w=800&auto=format&fit=crop"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "costa-bella-pinot-grigio",
        slug: "costa-bella-pinot-grigio",
        name: "Costa Bella Pinot Grigio",
        brand: "Costa Bella",
        category: "wine",
        subCategory: "white",
        price: 10.52,
        size: "1.5 L",
        abv: 12,
        images: ["https://images.unsplash.com/photo-1572569680370-49658253b92f?q=80&w=800&auto=format&fit=crop"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
    {
        id: "louis-roederer-cristal",
        slug: "louis-roederer-cristal-millesime-brut-bottle",
        name: "Louis Roederer Cristal Millesime Brut Bottle",
        brand: "Louis Roederer",
        category: "wine",
        subCategory: "champagne",
        price: 350.99,
        size: "750 ml",
        abv: 12,
        images: ["https://images.unsplash.com/photo-1594146669919-1df30448c682?q=80&w=800&auto=format&fit=crop"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: ["premium", "bubbly"],
    },
    {
        id: "elmo-pio-peach",
        slug: "elmo-pio-sweet-peach-flavored-wine",
        name: "Elmo Pio Sweet Peach Flavored Wine",
        brand: "Elmo Pio",
        category: "wine",
        subCategory: "fruit-wine",
        price: 10.52,
        size: "750 ml",
        abv: 7,
        images: ["https://images.unsplash.com/photo-1620861113524-ec5d07010534?q=80&w=800&auto=format&fit=crop"],
        inStock: true,
        isAlcohol: true,
        variants: [],
        tags: [],
    },
];
